# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gf-locator1'
         # metrics_path defaults to '/metrics'
         # scheme defaults to 'http'.

    static_configs:
      - targets: ['gf-locator1:8001']
    fallback_scrape_protocol: PrometheusText0.0.4



  - job_name: 'gf-locator2'
         # metrics_path defaults to '/metrics'
         # scheme defaults to 'http'.

    static_configs:
      - targets: ['gf-locator2:8002']
    fallback_scrape_protocol: PrometheusText0.0.4



  - job_name: 'gf-server1'
         # metrics_path defaults to '/metrics'
         # scheme defaults to 'http'.

    static_configs:
      - targets: ['gf-server1:8003']
    fallback_scrape_protocol: PrometheusText0.0.4



  - job_name: 'gf-server2'
         # metrics_path defaults to '/metrics'
         # scheme defaults to 'http'.

    static_configs:
      - targets: ['gf-server2:8004']
    fallback_scrape_protocol: PrometheusText0.0.4



  - job_name: 'gf-server3'
         # metrics_path defaults to '/metrics'
         # scheme defaults to 'http'.

    static_configs:
      - targets: ['gf-server3:8005']
    fallback_scrape_protocol: PrometheusText0.0.4
