apiVersion: gemfire.vmware.com/v1
kind: GemFireCluster
metadata:
  name: gemfire1
spec:
  image: registry.packages.broadcom.com/pivotal-gemfire/vmware-gemfire:10.1.2
  security:
    tls:
      secretName: my-secret-tls
      clientAuthenticationRequired: false
  locators:
    replicas: 1
  servers:
    replicas: 1
