services:

  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    hostname: openldap
    restart: unless-stopped
    networks:
      - gf-network
    environment:
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: password
      LDAP_USERS: user01,user02
      LDAP_PASSWORDS: password,password
      LDAP_ROOT: dc=example,dc=com
      LDAP_ADMIN_DN: cn=admin,dc=example,dc=com
    ports:
      - "1389:1389"

  gemfire-management-console:
    image: registry.packages.broadcom.com/gemfire-management-console/gemfire-management-console:1.3.0
    container_name: gemfire-management-console
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - gf-network

  gf-locator1:
    image: gemfire/gemfire:9.15.6
    container_name: gf-locator1
    environment:
      - ACCEPT_TERMS=y
    networks:
      - gf-network
    volumes:
      - ./gf-locator1:/data
    ports:
      - "10334:10334"
      - "7070:7070"
    command: gfsh start locator --name=gf-locator1
    restart: unless-stopped

  gf-locator2:
    image: gemfire/gemfire:9.15.6
    container_name: gf-locator2
    environment:
      - ACCEPT_TERMS=y
    networks:
      - gf-network
    volumes:
      - ./gf-locator2:/data
    ports:
      - "10335:10334"
      - "7071:7070"
    command: gfsh start locator --name=gf-locator2 --locators=gf-locator1[10334]
    depends_on:
      - gf-locator1
    restart: unless-stopped

  gf-server1:
    image: gemfire/gemfire:9.15.6
    container_name: gf-server1
    environment:
      - ACCEPT_TERMS=y
    networks:
      - gf-network
    volumes:
      - ./gf-server1:/data
    ports:
      - "40404:40404"
    command: gfsh start server --name=gf-server1 --locators=gf-locator1[10334]
    depends_on:
      - gf-locator1
    restart: unless-stopped

  gf-server2:
    image: gemfire/gemfire:9.15.6
    container_name: gf-server2
    environment:
      - ACCEPT_TERMS=y
    networks:
      - gf-network
    volumes:
      - ./gf-server2:/data
    ports:
      - "40405:40404"
    command: gfsh start server --name=gf-server2 --locators=gf-locator1[10334]
    depends_on:
      - gf-locator1
    restart: unless-stopped

  gf-server3:
    image: gemfire/gemfire:9.15.6
    container_name: gf-server3
    environment:
      - ACCEPT_TERMS=y
    networks:
      - gf-network
    volumes:
      - ./gf-server3:/data
    ports:
      - "40406:40404"
    command: gfsh start server --name=gf-server3 --locators=gf-locator1[10334]
    depends_on:
      - gf-locator1
    restart: unless-stopped

networks:
  gf-network:
    driver: bridge
