services:



  gf-locator1:
    image: gemfire/gemfire:10.0.2
    container_name: gf-locator1
    hostname: gf-locator1
    environment:
      - ACCEPT_TERMS=y
    networks:
      - gf-network
    volumes:
      - ./gf-locator1:/data
    ports:
      - "10334:10334"
      - "7070:7070"
      - "8001:8001"
    command: gfsh start locator --name=gf-locator1 --classpath=/gemfire/tools/Modules/gemfire-prometheus-metrics/* --J=-Dgemfire.prometheus.metrics.emission=Default --J=-Dgemfire.prometheus.metrics.port=8001
    restart: unless-stopped



  gf-server1:
    image: gemfire/gemfire:10.0.2
    container_name: gf-server1
    hostname: gf-server1
    environment:
      - ACCEPT_TERMS=y
    networks:
      - gf-network
    volumes:
      - ./gf-server1:/data
    ports:
      - "40404:40404"
      - "8003:8003"
    command: gfsh start server --name=gf-server1 --locators=gf-locator1[10334] --classpath=/gemfire/tools/Modules/gemfire-prometheus-metrics/* --J=-Dgemfire.prometheus.metrics.emission=Default --J=-Dgemfire.prometheus.metrics.port=8003
    depends_on:
      - gf-locator1
    restart: unless-stopped

  gf-server2:
    image: gemfire/gemfire:10.0.2
    container_name: gf-server2
    hostname: gf-server2
    environment:
      - ACCEPT_TERMS=y
    networks:
      - gf-network
    volumes:
      - ./gf-server2:/data
    ports:
      - "40405:40404"
      - "8004:8004"
    command: gfsh start server --name=gf-server2 --locators=gf-locator1[10334] --classpath=/gemfire/tools/Modules/gemfire-prometheus-metrics/* --J=-Dgemfire.prometheus.metrics.emission=Default --J=-Dgemfire.prometheus.metrics.port=8004
    depends_on:
      - gf-locator1
    restart: unless-stopped

  gf-server3:
    image: gemfire/gemfire:10.0.2
    container_name: gf-server3
    hostname: gf-server3                # specify the hostname
    environment:
      - ACCEPT_TERMS=y
    networks:
      - gf-network
    volumes:
      - ./gf-server3:/data
    ports:
      - "40406:40404"
      - "8005:8005"
    command: gfsh start server --name=gf-server3 --locators=gf-locator1[10334] --classpath=/gemfire/tools/Modules/gemfire-prometheus-metrics/* --J=-Dgemfire.prometheus.metrics.emission=Default --J=-Dgemfire.prometheus.metrics.port=8005
    depends_on:
      - gf-locator1
    restart: unless-stopped

  busybox:
    image: busybox:latest
    container_name: busybox
    hostname: busybox
    command: sh -c "while true; do sleep 3600; done"
    networks:
      - gf-network
    restart: unless-stopped

networks:
  gf-network:
    driver: bridge
